name: Maven CI

on:
  workflow_dispatch: { }
  push:
    branches-ignore:
      - 'renovate/*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt-openj9

      - name: Build with Maven
        run: ./mvnw --show-version --errors --batch-mode --no-transfer-progress verify -Pdocs

      - name: Check Liberty recognized localBindAddress
        shell: bash
        run: |
          # informational
          grep "CWWKG0074E" target/liberty/wlp/usr/servers/liberty.issue.20971Server/logs/messages.log || true
          # now the actual test
          test "$(grep -c "CWWKG0074E" target/liberty/wlp/usr/servers/liberty.issue.20971Server/logs/messages.log)" -eq 0
          test "$(grep -c "CWWKG0074E" target/liberty/wlp/usr/servers/liberty.issue.20971Server/logs/console.log)" -eq 0
